LINK_TIME_OPTIMIZATION_ENABLE = yes
COMMAND_ENABLE = no
UNICODE_ENABLE = yes
WEBUSB_ENABLE = no
SRC = matrix.c
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
LEADER_ENABLE = yes
# steno
MOUSEKEY_ENABLE = yes
STENO_ENABLE = yes
NKRO_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
MIDI_ENABLE = no

